// react-web/src/components/Header.jsx
import React from "react";
import { useNavigate } from 'react-router-dom';
import { AppBar, Toolbar, IconButton, Typography, Button, Container, Box } from "@mui/material";
import MenuIcon from "@mui/icons-material/Menu";
import AddShoppingCartIcon from '@mui/icons-material/AddShoppingCart';

const Header = () => {
    const navigate = useNavigate();

    const handleButtonClick = (pageURL) => {
        navigate(pageURL);
    };

    const menuItems = [
        { menuTitle: "Registracija", pageURL: "/register" },
        { menuTitle: "Profile", pageURL: "/profile" },
        { menuTitle: "Kontakti", pageURL: "/contacts" },
        { menuTitle: "Iziet", pageURL: "/logout" }
    ];

    const onLogout = () => {
        window.localStorage.removeItem('auth');
        navigate('/');
    };

    const openCart = () => {
        navigate('/cart');
    };

    return (
        <AppBar position="static" sx={{ bgcolor: "green" }}>
            <Container maxWidth="xl">
                <Toolbar disableGutters>
                    <Typography
                        variant="h5"
                        noWrap
                        component="a"
                        href=""
                        onClick={(e) => {
                            e.preventDefault();
                            navigate('/');
                        }}
                        sx={{
                            mr: 2,
                            display: { xs: 'flex', md: 'flex' },
                            flexGrow: 1,
                            fontFamily: "monospace",
                            fontWeight: 700,
                            letterSpacing: ".3rem",
                            color: "inherit",
                            textDecoration: "none"
                        }}
                    >
                        Veikals
                    </Typography>
                    {menuItems.map((menuItem, index) => (
                        <Button
                            key={index}
                            sx={{ my: 2, color: 'white', display: 'block' }}
                            onClick={() => menuItem.pageURL === "/logout" ? onLogout() : handleButtonClick(menuItem.pageURL)}
                        >
                            {menuItem.menuTitle}
                        </Button>
                    ))}
                    <IconButton
                        size="large"
                        edge="end"
                        color="inherit"
                        aria-label="shopping cart"
                        onClick={openCart}
                    >
                        <AddShoppingCartIcon />
                    </IconButton>
                </Toolbar>
            </Container>
        </AppBar>
    );
};

export default Header;

// vue-web/src/components/Header.vue
<template>
    <header class="app-header">
      <nav class="navbar">
        <div class="logo" @click="navigateTo('/')">Veikals</div>
        <ul class="nav-links">
          <li v-for="(item, index) in menuItems" :key="index">
            <a href="" @click.prevent="handleButtonClick(item.pageURL)">
              {{ item.menuTitle }}
            </a>
          </li>
        </ul>
        <button class="cart-button" @click="openCart">
          Cart
        </button>
      </nav>
    </header>
  </template>
  
  <script setup>
  import { useRouter } from 'vue-router';
  
  const router = useRouter();
  
  const menuItems = [
    { menuTitle: "Registracija", pageURL: "/register" },
    { menuTitle: "Profile", pageURL: "/profile" },
    { menuTitle: "Kontakti", pageURL: "/contacts" },
    { menuTitle: "Iziet", pageURL: "/logout" },
  ];
  
  const navigateTo = (url) => {
    router.push(url);
  };
  
  const handleButtonClick = (pageURL) => {
    if (pageURL === "/logout") {
      window.localStorage.removeItem('auth');
      navigateTo('/');
    } else {
      navigateTo(pageURL);
    }
  };
  
  const openCart = () => {
    navigateTo('/cart');
  };
  </script>
  
  <style scoped>
  .app-header {
    background-color: green;
    color: white;
  }
  
  .navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.5rem 1rem;
  }
  
  .logo {
    cursor: pointer;
    font-weight: bold;
    font-size: 1.5rem;
  }
  
  .nav-links {
    list-style: none;
    display: flex;
    gap: 1rem;
  }
  
  .nav-links a {
    color: white;
    text-decoration: none;
    transition: color 0.3s ease;
  }
  
  .nav-links a:hover {
    color: #ccc;
  }
  
  .cart-button {
    background: none;
    border: none;
    color: white;
    cursor: pointer;
    transition: color 0.3s ease;
  }
  
  .cart-button:hover {
    color: #ccc;
  }
  </style>
