// vue-web/src/components/Catalog.vue
<template>
    <div class="product-list">
      <div class="product" v-for="(product, index) in products" :key="index">
        <div class="card">
          <div class="card-content">
            <h5>{{ product.name }}</h5>
            <p>{{ product.price }}</p>
            <ul>
              <li v-for="(detail, i) in product.details" :key="i">{{ detail }}</li>
            </ul>
          </div>
          <div class="card-actions">
            <button @click="addToCart(product)">Pievienot grozam</button>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  export default {
    name: 'Catalog',
    data() {
      return {
        products: [
        {
        "name": "HP 250 G10 portatīvais dators",
        "price": "629,00 € / gab.",
        "details": [
          "Intel® Core™ i5-1335U, 16 GB, 512 GB, 15.6″, Intel Iris Xe Graphics, sudraba",
          "Ekrāna diagonāle: 15.6″",
          "Operētājsistēma: Windows 11",
          "Operatīvā atmiņa (RAM): 16 GB",
          "SSD/eMMC diska tilpums: 512 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Acer Aspire 5 portatīvais dators",
        "price": "550,00 € / gab.",
        "details": [
          "AMD Ryzen 5 3500U, 8 GB, 256 GB SSD, Vega 8, 15.6″, melns",
          "Ekrāna diagonāle: 15.6″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Dell G3 spēļu portatīvais dators",
        "price": "990,00 € / gab.",
        "details": [
          "Intel® Core™ i7-10750H, 16 GB, 1 TB SSD, NVIDIA GeForce GTX 1650 4GB, 15.6″, melns",
          "Ekrāna diagonāle: 15.6″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 16 GB",
          "SSD diska tilpums: 1 TB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "ASUS ZenBook 14 ultrabooks",
        "price": "1200,00 € / gab.",
        "details": [
          "Intel® Core™ i5-10210U, 8 GB, 512 GB SSD, Intel UHD Graphics, 14″, zils",
          "Ekrāna diagonāle: 14″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 512 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Lenovo Yoga 7 pārveidojams portatīvais dators",
        "price": "1050,00 € / gab.",
        "details": [
          "Intel® Core™ i5-1135G7, 16 GB, 512 GB SSD, Intel Iris Xe Graphics, 14″, sudraba",
          "Ekrāna diagonāle: 14″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 16 GB",
          "SSD diska tilpums: 512 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Microsoft Surface Laptop 4 portatīvais dators",
        "price": "1450,00 € / gab.",
        "details": [
          "AMD Ryzen 5 4680U, 8 GB, 256 GB SSD, AMD Radeon Graphics, 13.5″, platīna",
          "Ekrāna diagonāle: 13.5″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "MacBook Air M1",
        "price": "999,00 € / gab.",
        "details": [
          "Apple M1 čips, 8 GB, 256 GB SSD, 13.3″, zeltains",
          "Ekrāna diagonāle: 13.3″",
          "Operētājsistēma: macOS",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Samsung Galaxy Book S",
        "price": "850,00 € / gab.",
        "details": [
          "Intel® Core™ i5-L16G7, 8 GB, 256 GB SSD, Intel UHD Graphics, 13.3″, zeltains",
          "Ekrāna diagonāle: 13.3″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "ASUS TUF Gaming F15 spēļu portatīvais dators",
        "price": "1100,00 € / gab.",
        "details": [
          "Intel® Core™ i7-11800H, 16 GB, 512 GB SSD, NVIDIA GeForce RTX 3050 Ti, 15.6″, melns",
          "Ekrāna diagonāle: 15.6″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 16 GB",
          "SSD diska tilpums: 512 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "HP Pavilion x360 pārveidojams portatīvais dators",
        "price": "750,00 € / gab.",
        "details": [
          "Intel® Core™ i5-1135G7, 8 GB, 256 GB SSD, Intel Iris Xe Graphics, 14″, sudraba",
          "Ekrāna diagonāle: 14″",
          "Operētājsistēma: Windows 11",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      }
        ],
      };
    },
    methods: {
      addToCart(product) {
        let cart = JSON.parse(localStorage.getItem('cart')) || [];
        let found = cart.find(p => p.name === product.name);
        
        if (found) {
          found.quantity++;
        } else {
          cart.push({ ...product, quantity: 1 });
        }
        localStorage.setItem('cart', JSON.stringify(cart));
      },
    },
  };
  </script>
  
  <style scoped>
  .catalog-container {
    display: flex;
    justify-content: space-between;
  }
  .product-list {
  display: flex; 
  flex-wrap: wrap; 
  justify-content: space-between; 
  gap: 20px; 
  }
  .cart {
    width: 20%;
    border-left: 2px solid #ccc;
    padding-left: 20px;
  }
  .product {
  width: calc(33.333% - 20px); 
  margin-bottom: 20px; 
  }
  .card {
    border: 1px solid #ddd;
    padding: 15px;
    border-radius: 8px;
  }
  .card-content h5 {
    margin: 0;
    color: #333;
  }
  .card-content ul {
    padding-left: 20px;
  }
  .card-actions {
    margin-top: 10px;
  }
  .cart-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
  }
  @media (max-width: 1200px) {
  .product {
    width: calc(50% - 20px); 
  }
}

@media (max-width: 768px) {
  .product {
    width: 100%;
  }
}
  </style>

// react-web/src/Catalog.jsx
import React from 'react';
import { Grid, Card, CardContent, Typography, CardActions, Button } from '@mui/material';
const products = [
      {
        "name": "HP 250 G10 portatīvais dators",
        "price": "629,00 € / gab.",
        "details": [
          "Intel® Core™ i5-1335U, 16 GB, 512 GB, 15.6″, Intel Iris Xe Graphics, sudraba",
          "Ekrāna diagonāle: 15.6″",
          "Operētājsistēma: Windows 11",
          "Operatīvā atmiņa (RAM): 16 GB",
          "SSD/eMMC diska tilpums: 512 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Acer Aspire 5 portatīvais dators",
        "price": "550,00 € / gab.",
        "details": [
          "AMD Ryzen 5 3500U, 8 GB, 256 GB SSD, Vega 8, 15.6″, melns",
          "Ekrāna diagonāle: 15.6″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Dell G3 spēļu portatīvais dators",
        "price": "990,00 € / gab.",
        "details": [
          "Intel® Core™ i7-10750H, 16 GB, 1 TB SSD, NVIDIA GeForce GTX 1650 4GB, 15.6″, melns",
          "Ekrāna diagonāle: 15.6″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 16 GB",
          "SSD diska tilpums: 1 TB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "ASUS ZenBook 14 ultrabooks",
        "price": "1200,00 € / gab.",
        "details": [
          "Intel® Core™ i5-10210U, 8 GB, 512 GB SSD, Intel UHD Graphics, 14″, zils",
          "Ekrāna diagonāle: 14″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 512 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Lenovo Yoga 7 pārveidojams portatīvais dators",
        "price": "1050,00 € / gab.",
        "details": [
          "Intel® Core™ i5-1135G7, 16 GB, 512 GB SSD, Intel Iris Xe Graphics, 14″, sudraba",
          "Ekrāna diagonāle: 14″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 16 GB",
          "SSD diska tilpums: 512 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Microsoft Surface Laptop 4 portatīvais dators",
        "price": "1450,00 € / gab.",
        "details": [
          "AMD Ryzen 5 4680U, 8 GB, 256 GB SSD, AMD Radeon Graphics, 13.5″, platīna",
          "Ekrāna diagonāle: 13.5″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "MacBook Air M1",
        "price": "999,00 € / gab.",
        "details": [
          "Apple M1 čips, 8 GB, 256 GB SSD, 13.3″, zeltains",
          "Ekrāna diagonāle: 13.3″",
          "Operētājsistēma: macOS",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "Samsung Galaxy Book S",
        "price": "850,00 € / gab.",
        "details": [
          "Intel® Core™ i5-L16G7, 8 GB, 256 GB SSD, Intel UHD Graphics, 13.3″, zeltains",
          "Ekrāna diagonāle: 13.3″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "ASUS TUF Gaming F15 spēļu portatīvais dators",
        "price": "1100,00 € / gab.",
        "details": [
          "Intel® Core™ i7-11800H, 16 GB, 512 GB SSD, NVIDIA GeForce RTX 3050 Ti, 15.6″, melns",
          "Ekrāna diagonāle: 15.6″",
          "Operētājsistēma: Windows 10",
          "Operatīvā atmiņa (RAM): 16 GB",
          "SSD diska tilpums: 512 GB"
        ],
        "availability": "Pievienot grozam"
      },
      {
        "name": "HP Pavilion x360 pārveidojams portatīvais dators",
        "price": "750,00 € / gab.",
        "details": [
          "Intel® Core™ i5-1135G7, 8 GB, 256 GB SSD, Intel Iris Xe Graphics, 14″, sudraba",
          "Ekrāna diagonāle: 14″",
          "Operētājsistēma: Windows 11",
          "Operatīvā atmiņa (RAM): 8 GB",
          "SSD diska tilpums: 256 GB"
        ],
        "availability": "Pievienot grozam"
      }
  ];
  
  const Catalog = ({ addToCart }) => {
    return (
      <Grid container spacing={4}>
        {products.map((product, index) => (
          <Grid item xs={12} sm={6} md={4} lg={3} key={index}>
            <Card>
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">
                  {product.name}
                </Typography>
                <Typography variant="body2" color="text.secondary" component="div">
                  {product.details.map((detail, i) => (
                    <div key={i}>{detail}</div>
                  ))}
                </Typography>
              </CardContent>
              <CardActions>
                <Button size="small">Skatīt vairāk</Button>
                <Button size="small" onClick={() => addToCart(product)}>Pievienot grozam</Button>
              </CardActions>
            </Card>
          </Grid>
        ))}
      </Grid>
    );
};

export default Catalog;
