// react/src/profile.js
import React from "react";
import { Container } from "@mui/system";
import Grid from "@mui/material/Grid";
import { Button, Typography } from "@mui/material";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Divider from "@mui/material/Divider";
import IMG from '../img/profile.png'
import CardMedia from "@mui/material/CardMedia";
import '../styles/img.css';

const theme = createTheme({
  palette: {
    primary: {
      main: "#9e9e9e",
    },
    secondary: {
      main: "#11cb5f",
    },
  },
});

export default function profile() {
  return (
    <>
      <Container maxWidth="xl" sx={{ display: "flex", height: "150px" }}>
        <Grid container xs={12} justifyContent="center" mt={10}>
          <Divider>Profile</Divider>
        </Grid>
      </Container>
      <Container maxWidth="xl">
        <Grid container xs={12} mt={3} justifyContent="space-between">
            <Grid item xs={12} mt={2}>
                <Typography>Vards:test</Typography>
            </Grid>
            <Grid item xs={12} mt={2}>
                <Typography>Uzvards:test</Typography>
            </Grid>
            <Grid item xs={12} mt={2}>
                <Typography>Tiesibas:Admin</Typography>
            </Grid>
            <Grid item xs={12} mt={2}>
                <Typography>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                </Typography>
            </Grid>
            <Grid item xs={12} mt={2}>
                <Typography>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </Typography>
            </Grid>
            <Grid item xs={12}>
            <CardMedia
              className="img"
              component="img"
              image={IMG}
              alt="Error"
            />
            </Grid>
        </Grid>
        <ThemeProvider theme={theme}>
          <Grid container xs={12}>
            <Grid item xs={12} md={1} mt={3}>
              <Button variant="contained" color="secondary" fullWidth>
                Edit
              </Button>
            </Grid>
          </Grid>
        </ThemeProvider>
      </Container>
    </>
  );
}

// angular-web/src/app/profile/profile.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent {
  profileData = {
    firstName: 'test',
    lastName: 'test',
    role: 'Admin',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
  };
}

<mat-card>
    <mat-card-content>
      <div class="container" style="max-width: xl;">
        <div class="text-center" style="margin-top: 40px;">
          <h4>Profile</h4>
        </div>
        <mat-divider style="margin-y: 30px;"></mat-divider>
  
        <div fxLayout="row" fxLayoutGap="20px" fxLayoutAlign="start center">
          <div fxFlex="12" fxFlex.gt-sm="6" fxFlex.gt-md="4">
            <mat-card>
              <mat-card-content>
                <h6>Personal Information</h6>
                <p>First Name: {{profileData.firstName}}</p>
                <p>Last Name: {{profileData.lastName}}</p>
                <p>Role: {{profileData.role}}</p>
              </mat-card-content>
            </mat-card>
          </div>
  
          <div fxFlex="12" fxFlex.gt-sm="6" fxFlex.gt-md="8">
            <mat-card>
              <mat-card-content>
                <h6>Biogrāfija</h6>
                <p>{{profileData.bio}}</p>
              </mat-card-content>
            </mat-card>
          </div>
        </div>
  
        <div style="margin-top: 20px;" fxLayout="row" fxLayoutGap="20px">
          <div fxFlex="12" fxFlex.gt-sm="4" fxFlex.gt-md="2">
            <button mat-raised-button color="primary">Rediģēt profilu</button>
          </div>
        </div>
      </div>
    </mat-card-content>
  </mat-card>
